### ISSUE TITLE
Build doesn't produce NuGet packages

### ISSUE THREAD

**Issue by TeaDrivenDev** [ReedCopsey/Gjallarhorn#10]
I wanted to build NuGet packages of Gjallarhorn (or preferably just use this as a NuGet souce via Paket), but apparently that doesn't work yet. I couldn't find out easily how NuGet creation via FAKE/Paket works, so I'll just put this here as a reminder for now.

I suppose you intend to have separate packages for the projects that build on each other; is that correct?

**Comment by ReedCopsey** [comment]
I haven't published NuGet packages (yet), since the API has been in flux quite a bit.  I've been hoping to get a couple more people looking at it to make sure it's reasonable before putting out packages, but definitely plan to do that.

> I suppose you intend to have separate packages for the projects that build on each other; is that correct?

Yes, that's the plan.  Likely will have a core package, binding package, and then platform specific package(s) (ie: for WPF, Xamarin/UWP, etc, since they require different binding target implementations).

**Comment by TeaDrivenDev** [comment]
Yeah, it doesn't make sense to have something on NuGet that early, but it would be nicer to use and trial in other projects if the build produced packages, because it would allow for referencing Gjallarhorn directly from GitHub with Paket.

**Comment by JohanLarsson** [comment]
@ReedCopsey If you want to you can publish a prerelease (0.X) package. The early adopters can perhaps tolerate a few API changes.

**Comment by jeroldhaas** [comment]
I'd just searched the other night for Gjallarhorn, so the timing is right to raise this issue. @ReedCopsey  has the repo reached a certain level of homeostasis yet? Even working with the project folder in another solution tends to muck up my organization. A prerelease would be a fitting idea.

**Comment by ReedCopsey** [comment]
@jeroldhaas @JohanLarsson @TeaDrivenDev Pushed prerelease to nuget: https://www.nuget.org/packages/Gjallarhorn.Bindable.Wpf/0.0.2-beta1

Let me know how it goes. The API will likely still change - I won't do a real release until it's stable, though I think it's getting "close" to stable.
