### ISSUE TITLE
Validation issue in Binding.mutateToFromViewValidated

### ISSUE THREAD

**Issue by kirill-gerasimenko** [ReedCopsey/Gjallarhorn#38]
Hi,

I'm not sure that this is really the issue or I'm missing something important. 

When I use `Binding.mutateToFromViewValidated` to bind mutable with some validation rule and the input is invalid the red border doesn't appear for the text box. The validation itself seems to be working.

I've created sample project to illustrate  - https://github.com/kirill-gerasimenko/TestMutateValidation
There are two textboxes, one is bound using `Binding.mutateToFromViewValidated`, other by using `Binding.toFromViewValidated`, they share the same validation rule. Former doesn't show validation error, the latter does. 

Would you be able to have a look at this?

Kirill

**Comment by FoggyFinder** [comment]
It seems like a bug to me, more simple mcve below:

```fsharp
let test() = 
    let value = Mutable.create ""

    use dynamicVm = Binding.createSource ()
    let validator = (notNullOrWhitespace >> hasLengthAtLeast 3)
    Binding.mutateToFromViewValidated dynamicVm "Value" validator value
    
    dynamicVm.IsValid |> printfn "empty string: %A" //true, should be false 
    value.Value <- "Valid"

    dynamicVm.IsValid |> printfn "Valid string : %A"  //true, should be true

    value.Value <- "-"
    dynamicVm.IsValid |> printfn "Invalid string : %A"  //true, should be false 
```

**Comment by FoggyFinder** [comment]
Okay, I guess I found why it happened. There a two reasons:
1. The part of code that responds for updating the mutable.
https://github.com/ReedCopsey/Gjallarhorn/blob/master/src/Gjallarhorn/IO.fs#L95-L99

it seems like updating only when changing validation result instead of just a value, so I think it should be something like that:

```fsharp
    let subscription = 
        validated
        |> Signal.Subscription.create(Option.iter(Mutable.set input))
```

2. About "decorator".
https://github.com/ReedCopsey/Gjallarhorn/blob/master/src/Gjallarhorn/IO.fs#L88-L89

`MutatableInOut` inherit `InOut` instead of `ValidatedInOut`, so there:

https://github.com/ReedCopsey/Gjallarhorn/blob/master/src/Gjallarhorn.Bindable/BindingSource.fs#L125-L128

can't be convert to `ValidatedInOut`

**Comment by ReedCopsey** [comment]
Thank you @FoggyFinder  - You were right about the underlying problem - changing the inheritance solved this. Added 2 new tests for this as well.

**Comment by kirill-gerasimenko** [comment]
Thank you for reacting to this so quickly and fixing the issue!
