### ISSUE TITLE
.Add notifies even when underlying value has not changed

### ISSUE THREAD

**Issue by charlesroddie** [ReedCopsey/Gjallarhorn#63]
Related to https://github.com/ReedCopsey/Gjallarhorn/issues/56 but simpler:
```fsharp
let x = Mutable.create false
x.Add(fun b -> Debug.WriteLine(sprintf "x is now %b" b))
x.Value <- false // does nothing, as expected, because x has not changed

let y = Mutable.create -1
let z = y |> Signal.map (fun y -> y < 0)
z.Add(fun b -> Debug.WriteLine(sprintf "z is now %b" b))
y.Value <- -2 // prints "z is now true", unexpectedly
y.Value <- -3 // prints "z is now true", unexpectedly
```

**Comment by FoggyFinder** [comment]
That's, probably, because of the way how `DependencyTracker` treats `IObserver<_>`:

```fs
depObservers |> Array.iter (signalObserver v)
```

---

There is a `Signal.Subscription.create` that will not notify if final value wasn't changed.

**Comment by ReedCopsey** [comment]
IObservable is supposed to notify in the case of the same value pushing through. Rx has "DistinctUntilChanged" (or Distinct) to handle this case. 

ISignal does not - by default, it implicity does a "distinct until changed" type of filter on it's signal propogation. In this case, since you're doing "z.Add", you're treating this as IObserable<_> instead of using Signal subscription, which doesn't "block" the duplicated "true" messages from propogating.

This behavior is by design. Dependency tracking has 2 paths specifically to keep observable management working like most other IObservable libraries.
